arla/arla/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static

from core.views import index, contact

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('item/', include('item.urls')),
    path('category/', include('category.urls')),
    path('cart/', include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

arla/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/', views.addToCart, name='add'),
    path('delete/', views.deleteFromCart, name='delete'),
    path('update/', views.updateCart, name='update'),
]

arla/core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm,), name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.LogoutView, name='logout'),
    path('browse/', views.browse, name='browse'),
    path('profile/', views.profile, name='profile'),
    path('settings/', views.settings, name='settings'),
    path('password/', views.password, name='password'),
]

arla/item/urls.py
from django.urls import path
from . import views


app_name = 'item'
urlpatterns = [
    path('<int:pk>/', views.item_list, name='detail'),
]

arla/item/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ['name',]
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    

class Item(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='items/item_images', blank=True, null=True)
    is_on_sale = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)

    class Meta:
        ordering = ['name',]

    def __str__(self):
        return self.name

arla/item/views.py
from django.shortcuts import render, get_object_or_404
from .models import Item

def item_list(request, pk):

    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category).exclude(pk=pk)[:3]

    return render(request, 'item/detail.html', {'item': item, 'related_items': related_items})

arla/item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }} | {% endblock %}

{% block content %}
    <div class="grid grid-cols-5 gap-6">
        <div class="sm:col-span-3 col-span-5">
            <img src="{{ item.image.url }}" alt="{{ item.name }}" class="rounded-xl h-full">
        </div>
        <div class="sm:col-span-2 col-span-5 p-6 bg-gray-100 rounded-xl">
            <h1 class="sm:mb-6 mb-3 sm:text-3xl text-lg font-bold">{{ item.name }}</h1>
            <p id="price" class="sm:text-lg text-md text-gray-500"><strong>Price:</strong> ${{ item.price }}</p>
            {% if item.description %}
            <p class="text-gray-500 mb-3"><strong>Description:</strong> {{ item.description }}</p>
            {% endif %}
            <form class="max-w-xs">
                {% csrf_token %}
                <div class="relative flex items-center max-w-[8rem]">
                    <button type="button" id="decrement-button" data-input-counter-decrement="quantity-input" class="bg-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 dark:border-gray-600 hover:bg-gray-200 border border-gray-300 rounded-s-lg p-3 h-11 focus:ring-gray-100 dark:focus:ring-gray-700 focus:ring-2 focus:outline-none">
                        <svg class="w-3 h-3 text-gray-900 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 2">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h16"/>
                        </svg>
                    </button>
                    <input type="text" id="quantity-input" data-input-counter aria-describedby="helper-text-explanation" class="bg-gray-50 border-x-0 border-gray-300 h-11 text-center text-gray-900 text-sm focus:ring-blue-500 focus:border-blue-500 block w-full py-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="1" value="1" required />
                    <button type="button" id="increment-button" data-input-counter-increment="quantity-input" class="bg-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 dark:border-gray-600 hover:bg-gray-200 border border-gray-300 rounded-e-lg p-3 h-11 focus:ring-gray-100 dark:focus:ring-gray-700 focus:ring-2 focus:outline-none">
                        <svg class="w-3 h-3 text-gray-900 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 18">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 1v16M1 9h16"/>
                        </svg>
                    </button>
                </div>
            </form>
            <div class="mt-6 grid grid-cols-2 gap-3">

                    <a href="#" class="px-6 py-3 text-sm font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">
                    <button value="{{ item.id }}" id="buy-now"><i class="fa-solid fa-credit-card fa-lg"></i> Buy Now</button>
                    </a>
                
                    {% if request.user.is_authenticated %}
                    <a href="#" class="px-6 py-3 text-sm font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">
                       <button value="{{ item.id }}" id="add-cart"><i class="fa-solid fa-shopping-cart fa-lg"></i> Add to Cart</button> 
                    </a>
                    {% else %}
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-sm font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">
                        <button value="{{ item.id }}" id="add-cart"><i class="fa-solid fa-shopping-cart fa-lg"></i> Add to Cart</button> 
                    </a>
                    {% endif %}

                
            </div>
        </div>
    </div>
    {% if related_items %}
    <div class="mt-6 grid sm:grid-cols-3 gap-3 ">
    <h4 class="col-span-3 text-xl font-semibold">More products from {{ item.category }} catalogue</h4>
        {% for product in related_items %}
            <div>
                <a href="{% url 'item:detail' product.id %}">
                    <div>
                        <img src="{{ product.image.url }}" alt="{{ product.name }}" class="rounded-t-xl">
                    </div>
                    <div  class="bg-white sm:p-6 p-3 rounded-b-xl shadow-md">
                        <h3 class="sm:text-2xl text-md">{{ product.name }}</h3>
                        <p class="text-gray-500"><strong>Price: ${{ product.price }}</strong></p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
    {% endif %}

<script>
    const decrementButton = document.getElementById('decrement-button');
    const incrementButton = document.getElementById('increment-button');
    const quantityInput = document.getElementById('quantity-input');

    decrementButton.addEventListener('click', () => {
        const currentValue = Number(quantityInput.value);
        const newValue = currentValue - 1;
        quantityInput.value = newValue >= 1 ? newValue : 1;
    });

    incrementButton.addEventListener('click', () => {
        const currentValue = Number(quantityInput.value);
        const newValue = currentValue + 1;
        quantityInput.value = newValue;
    });


    $(document).on('click', '#add-cart', function(e){
        e.preventDefault();
        
        $.ajax({
            type: 'POST',
            url: '{% url "cart:add" %}',
            data: {
                'item_id': $('#add-cart').val(),
                'quantity': $('#quantity-input').val(),
                'csrfmiddlewaretoken': '{{ csrf_token }}',
                'action': 'post'
            },
            success: function(response){
                document.getElementById('cart-qty').innerHTML = response['Quantity'];
                location.reload();
                // console.log(response);
                // alert('Item added to cart');
            },
            error: function(response){
                console.log(response);
                alert('Error adding item to cart');
            }
        });
    });
</script>

{% endblock %}