arla/arla/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static

from core.views import index, contact

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('item/', include('item.urls')),
    path('category/', include('category.urls')),
    path('cart/', include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

arla/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/', views.addToCart, name='add'),
    path('delete/', views.deleteFromCart, name='delete'),
    path('update/', views.updateCart, name='update'),
]

arla/category/urls.py
from django.urls import path
from . import views


app_name = 'category'
urlpatterns = [
    path('<str:name>/', views.item_in_category, name='category'),
]

arla/core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm,), name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.LogoutView, name='logout'),
    path('browse/', views.browse, name='browse'),
    path('profile/', views.profile, name='profile'),
    path('settings/', views.settings, name='settings'),
    path('password/', views.password, name='password'),
]

arla/item/urls.py
from django.urls import path
from . import views


app_name = 'item'
urlpatterns = [
    path('<int:pk>/', views.item_list, name='detail'),
]

arla/core/models.py
from django.db import models

# Create your models here.

arla/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, SetPasswordForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=50, help_text='Required', widget=forms.TextInput(attrs={'placeholder': 'Input Your Username', 'class': 'mb-5 w-full py-4 px-6 border border-black shadow-[5px_5px_0px_0px_rgba(0,0,0)] rounded-xl'}))

    password = forms.CharField(max_length=100, help_text='Required', widget=forms.PasswordInput(attrs={'placeholder': 'Input Your Password', 'class': 'mb-5 w-full py-4 px-6 border border-black shadow-[5px_5px_0px_0px_rgba(0,0,0)] rounded-xl'}))


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=100, help_text='Required', widget=forms.TextInput(attrs={'placeholder': 'Input Your Email', 'class': 'mb-5 w-full py-4 px-6 border border-blue-700 shadow-[5px_5px_0px_0px_rgba(29,78,216)] rounded-xl'}))

    first_name = forms.CharField(max_length=50, help_text='Required', widget=forms.TextInput(attrs={'placeholder': 'Input Your First Name', 'class': 'sm:w-4/5 w-full mb-5 py-4 px-6 border border-blue-700 shadow-[5px_5px_0px_0px_rgba(29,78,216)] rounded-xl'}))

    last_name = forms.CharField(max_length=50, help_text='Required', widget=forms.TextInput(attrs={'placeholder': 'Input Your Last Name', 'class': 'sm:w-4/5 w-full mb-5 py-4 px-6 border border-blue-700 shadow-[5px_5px_0px_0px_rgba(29,78,216)] rounded-xl'}))

    username = forms.CharField(max_length=50, help_text='Required', widget=forms.TextInput(attrs={'placeholder': 'Input Your Username', 'class': 'mb-5 w-full py-4 px-6 border border-blue-700 shadow-[5px_5px_0px_0px_rgba(29,78,216)] rounded-xl'}))

    password1 = forms.CharField(max_length=100, help_text='Required', widget=forms.PasswordInput(attrs={'placeholder': 'Input Your Password', 'class': 'mb-5 w-full py-4 px-6 border border-blue-700 shadow-[5px_5px_0px_0px_rgba(29,78,216)] rounded-xl'}))

    password2 = forms.CharField(max_length=100, help_text='Required', widget=forms.PasswordInput(attrs={'placeholder': 'Repeat Your Password', 'class': 'mb-5 w-full py-4 px-6 border border-blue-700 shadow-[5px_5px_0px_0px_rgba(29,78,216)] rounded-xl'}))


    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

class updateProfileForm(UserChangeForm):
    password = None  # Disable password field in the form
    email = forms.EmailField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Input Your Email', 'class': 'mb-2 w-full py-2 px-3 mt-1 border border-blue-700 shadow-[5px_5px_0px_0px_rgba(29,78,216)] rounded-xl'}))

    first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Input Your First Name', 'class': 'mb-2 w-full py-2 px-3 mt-1 border border-blue-700 shadow-[5px_5px_0px_0px_rgba(29,78,216)] rounded-xl'}))

    last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Input Your Last Name', 'class': 'mb-2 w-full py-2 px-3 mt-1 border border-blue-700 shadow-[5px_5px_0px_0px_rgba(29,78,216)] rounded-xl'}))

    username = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Input Your Username', 'class': 'mb-2 w-full py-2 px-3 mt-1 border border-blue-700 shadow-[5px_5px_0px_0px_rgba(29,78,216)] rounded-xl'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', )

class PasswordChangeForm(SetPasswordForm):
    new_password1 = forms.CharField(max_length=100,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Input Your New Password', 'class': 'mb-5 w-full py-2 px-3 border border-black shadow-[2px_2px_0px_0px_rgba(0,0,0)] rounded-xl'}))

    new_password2 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'placeholder': 'Repeat Your New Password', 'class': 'mb-5 w-full py-2 px-3 border border-black shadow-[2px_2px_0px_0px_rgba(0,0,0)] rounded-xl'}))

    class Meta:
        model = User
        fields = ('new_password1', 'new_password2')

arla/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib import messages
from django.db.models import Max
from django.contrib.auth.models import User


from item.models import Item, Category
from .forms import SignupForm, updateProfileForm, PasswordChangeForm

def index(request):
    items = Item.objects.all()[:6]
    category = Category.objects.all()

    context = {
        'items': items,
        'categories': category,
    }
    return render(request, 'core/index.html', context=context)

def contact(request):
    return render(request, 'core/contact.html')

def about(request):
    return render(request, 'core/about.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()
    return render(request, 'core/signup.html', {'form': form})

def LogoutView(request):
    logout(request)
    messages.success(request, 'You have been logged out.')
    return redirect('core:index')

def browse(request):
    items = Item.objects.all()
    max_price = Item.objects.aggregate(max_price=Max('price', default=0))
    category = Category.objects.all()
    context = {
        'items': items,
        'categories': category,
        'max_price': max_price['max_price'],
    }
    return render(request, 'core/browse.html', context=context)


def profile(request):
    if request.user.is_authenticated:
        user = User.objects.get(username=request.user)
        # profile_form = updateProfileForm(request.POST or None, instance=request.user)
        context = {
            'user': user,
            # 'profile_form': profile_form
        }
        return render(request, 'core/profile.html',context=context)
    else:
        messages.error(request, 'You need to be logged in to view your profile.')
        return redirect('core:login')


def settings(request):
    if request.user.is_authenticated:
        user = User.objects.get(username=request.user)
        profile_form = updateProfileForm(request.POST or None, instance=request.user)
        context = {
            'user': user,
            'profile_form': profile_form
        }

        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Profile updated successfully.')
            return redirect('core:profile')
        
        return render(request, 'core/settings.html',context=context)
    else:
        messages.error(request, 'You need to be logged in to view your profile.')
        return redirect('core:login')
    

def password(request):
    if request.user.is_authenticated:
        user = request.user
        password_form = PasswordChangeForm(user=user, data=request.POST)
        context = {
            'user': user,
            'password_form': password_form
        }

        if request.method == 'POST':
            if password_form.is_valid():
                password_form.save()
                messages.success(request, 'Password updated successfully.')
                return redirect('core:login')
            else:
                for error in list(password_form.errors.values()):
                    messages.error(request, error)

        return render(request, 'core/password.html', context=context)
    else:
        messages.error(request, 'You need to be logged in to change your password.')
        return redirect('core:login')

arla/core/templates/core/about.html
{% extends 'core/base.html' %}


{% block content %}
<div class="sm:w-3/4 w-full mx-auto my-7 px-6 py-12 bg-gray-100 rounded-xl">
    <h1 class="text-3xl font-semibold text-center mb-3">About Us</h1>
    <p class="sm:text-lg text-xs px-6 py-4 text-gray-500 mb-4">ARLA Racing Exhaust is a company that specializes in the production of high-quality exhaust systems for motorcycles. We have been in the business for over 20 years and have built a reputation for providing top-notch products and excellent customer service. Our exhaust systems are designed to improve the performance and sound of your motorcycle while also enhancing its appearance. We take pride in our work and are committed to delivering the best products to our customers. If you have any questions or would like to learn more about our products, please feel free to contact us.</p>
    <div class="w-full flex items-center mb-5">
        <a href="{% url 'core:contact' %}" class="mx-auto font-semibold py-4 px-3 rounded-lg border border-black shadow-[5px_5px_0px_0px_rgba(0,0,0)] hover:bg-blue-700 hover:text-white hover:shadow-[5px_5px_0px_0px_rgba(0,0,0)]">Contact Us</a>
    </div>
    <div class="w-full flex items-center justify-center">
        <span class="text-gray-500 text-semibold">Follow Us on Socials</span>
    </div>
    <div class="w-full flex items-center justify-center mt-3">
        <a href="https://web.facebook.com/p/ARLA-recing-exhaust-indonesia-100090862470244/?_rdc=1&_rdr#" target="_blank" class="mx-2 text-2xl text-blue-700 hover:text-blue-900"><i class="fa-brands fa-facebook fa-lg"></i></a>
        <a href="https://www.instagram.com/bayuarlaexhaust" target="_blank" class="mx-2 text-2xl text-red-500 hover:text-red-700"><i class="fa-brands fa-instagram fa-lg"></i></a>
        <a href="https://www.tiktok.com/@arlaracingexhaustidn" target="_blank" class="mx-2 text-2xl text-blue-400 hover:text-blue-600"><i class="fa-brands fa-tiktok fa-lg"></i></a>
    </div>

</div>
{% endblock %}

arla/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'icons/favicon.ico?123456789' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}ARLA Exhaust</title>
</head>

<body>
    <nav class="py-6 sm:px-6 p-1 flex justify-between items-center border-b border-gray-200">
        <a href="/"><img src="{% static 'assets/logo.webp' %}" alt="ARLA Logo" class="sm:w-full w-1/2 pt-4"></a>
        <div class="sm:space-x-4 space-x-2">
            <a href="{% url 'core:browse' %}" class="sm:text-lg text-xs font-semibold hover:text-gray-500"><i class="fa-solid fa-compass fa-md"></i> Browse</a>
            
            {% if request.user.is_authenticated %}

            <a href="{% url 'cart:cart' %}" class="sm:text-lg text-xs font-semibold hover:text-gray-500"><i class="fa-solid fa-shopping-cart fa-md"></i> Cart <span id="cart-qty" class="sm:inline hidden py-1 px-2 font-semibold text-white text-xs bg-red-500 rounded-full">{{ cart|length }}</span></a>

            <button id="dropdownAvatarNameButton" data-dropdown-toggle="dropdownAvatarName" class="text-sm pe-1 font-medium hover:text-gray-500" type="button">
                <p class="sm:text-lg text-xs"><i class="fa-solid fa-bars fa-md"></i></p>
            </button>
            <div id="dropdownAvatarName" class="relative right-0 z-9999 hidden bg-white divide-y divide-gray-100 rounded-lg shadow-sm w-1/8 dark:bg-gray-700 dark:divide-gray-600">
                <ul class="absolute right-0 bg-white mt-2 sm:-mx-6 -mx-1 border border-gray-200 rounded-xl py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownInformdropdownAvatarNameButtonationButton">
                    <li>
                    <a href="{% url 'core:profile' %}" class="block px-4 py-2 sm:text-lg text-xs hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"><i class="fa-solid fa-user"></i> Profile</a>
                    </li>
                    <li>
                    <a href="{% url 'core:settings' %}" class="block px-4 py-2 sm:text-lg text-xs hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"><i class="fa-solid fa-cog fa-md"></i> Settings</a>
                    </li>
                    <li>
                    <a href="/logout/" class="block px-4 py-2 sm:text-lg text-xs hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"><i class="fa-solid fa-sign-out fa-md"></i> Logout</a>
                    </li>
                </ul>
            </div>
            


            {% else %}
            <a href="{% url 'core:signup' %}" class="sm:py-2 py-1 sm:px-3 px-1 sm:text-lg text-xs font-semibold sm:rounded-xl rounded-lg bg-white border border-blue-700 text-blue-700 shadow-[2px_2px_0px_0px_rgba(29,78,216)] hover:bg-blue-700 hover:text-white hover:shadow-[2px_2px_0px_0px_rgba(0,0,0)]">Sign Up</a>
            <a href="{% url 'core:login' %}" class="sm:py-2 py-1 sm:px-3 px-1 sm:text-lg text-xs font-semibold sm:rounded-xl rounded-lg bg-white border border-black text-black shadow-[2px_2px_0px_0px_rgba(0,0,0)] hover:bg-blue-700 hover:text-white hover:shadow-[2px_2px_0px_0px_rgba(0,0,0)]">Login</a>
            {% endif %}
        </div>

    </nav>
    {% if messages %}
        {% for message in messages %}
        <div class="bg-yellow-100 border border-yellow-400 text-yellow-700 px-4 py-3 rounded relative" role="alert">
            <span class="block sm:inline">{{ message }}</span>
            <span class="absolute top-0 bottom-0 right-0 px-4 py-3" onclick="this.parentElement.style.display='none'">
              <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
            </span>
        </div>
        {% endfor %}
    {% endif %}
    
    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="py-6 px-6 bg-gray-800">
        <div class="flex justify-between">
            <div class="w-2/3 pr-10">
                <h3 class="mb-1 font-semibold text-gray-400 ">Arla Racing Exhaust Indonesia</h3>
                <p class="sm:text-md text-xs text-gray-500">Pesanggrahan RT.04/RW.3, Area Sawah, Bojanegara, Kecamatan Padamara,<br> Kabupaten Purbalingga, Jawa Tengah 53372</p>
            </div>
            <div class="w1/3 ">
                <h3 class="mb-1 font-semibold text-gray-400 ">Menu</h3>
                <ul>
                    <li><a href="{% url 'core:about' %}" class="sm:text-md text-sm text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="sm:text-md text-sm text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="sm:text-md text-sm text-teal-500 hover:text-teal-700">Terms of Use</a></li>
                </ul>
            </div>
        </div>
            <p class="sm:text-md text-xs text-gray-500">&copy;Copyright Arla Racing Exhaust Indonesia</p>
    </footer>
    <script>
        $(document).ready(function(){
            $('#dropdownAvatarNameButton').click(function(){
                $('#dropdownAvatarName').toggle();
            });
        });
    
    </script>

</body>
</html>

arla/core/templates/core/browse.html
{% extends 'core/base.html' %}



{% block content %}

<div class="sm:w-3/4 w-full mx-auto my-7 px-3 py-4 space-x-3 bg-gray-100 rounded-xl">
    <div class="grid sm:grid-cols-5 gap-5 p-4">
        <div id="checkbox" class="col-start-1 col-span-1 p-3 bg-white rounded-lg shadow dark:bg-gray-700">
          <h6 class="mb-3 text-sm font-medium text-gray-900 dark:text-white">Category</h6>

        <!-- Checkbox menu -->
          <ul class="space-y-2 text-sm mb-2 pb-3 border-b-2 border-gray-300" aria-labelledby="dropdownDefault">
            {% for category in categories %}
            <li class="flex items-center">
                <input id="{{ category }}" type="checkbox" value=""
                  class="w-4 h-4 bg-gray-100 border-gray-300 rounded text-primary-600 focus:ring-primary-500 dark:focus:ring-primary-600 dark:ring-offset-gray-700 focus:ring-2 dark:bg-gray-600 dark:border-gray-500" />
        
                <label for="{{ category }}" class="ml-2 text-sm font-medium text-gray-900 dark:text-gray-100">
                  {{ category }} ({{category.items.count}})
                </label>
            </li>
            {% endfor %}
          </ul>
        <!-- End Checkbox menu -->



        <!-- Price Range -->
          <div class="bg-white w-full max-w-md pb-3 border-b-2 border-gray-300 mb-2">
            <div class="mb-1">
              <label for="price-range" class="block text-sm p-0 text-gray-900 mb-2">Price Range</label>
              <input type="range" id="price-range" class="w-full accent-indigo-600" min="0" max="{{ max_price }}" value="50" oninput="updatePrice(this.value)">
            </div>
            <div class="flex justify-between text-gray-500 mb-1">
              <span id="minPrice" class="text-xs">$0</span>
              <span id="maxPrice" class="text-xs">${{max_price}}</span>
            </div>
          </div>
        <!-- End Price Range -->
         <button class="text-sm bg-blue-700 text-white rounded-xl py-2 px-3 hover:bg-blue-500">Show Products</button>
        </div>


        <div class="col-start-2 col-span-4">
            <div class="grid sm:grid-cols-2 gap-3">
              {% for product in items %}
              <div classs="">
                <a href="{% url 'item:detail' product.id %}">
                  <div>
                    <img src="{{ product.image.url }}" alt="{{ product.name }}" class="rounded-t-xl w-full">
                  </div>
                  <div  class="bg-white sm:p-6 p-2 rounded-b-xl shadow-md">
                    <h3 class="sm:text-2xl text-md">{{ product.name }}</h3>
                    <p class="sm:text-md text-sm text-gray-500">Price: ${{ product.price }}</p>
                  </div>
                </a>
              </div>
              {% endfor %}
            </div>
        </div>


        <script>
          const checkboxes = document.querySelectorAll('input[type="checkbox"]');
          console.log(checkboxes);

          let arr = [];

          // Check if any checkbox is checked on page load
          // Add event listeners to checkboxes
          checkboxes.forEach(checkbox => {
            checkbox.addEventListener('change', () => {
              if (checkbox.checked) {
                // console.log(checkbox.id);
                arr.push(checkbox.id);
                // console.log(arr);
              } else {
                // console.log('Unchecked: ' + checkbox.id);
                arr = arr.filter(item => item !== checkbox.id);
                // console.log(arr);
              }
            });
          });

          


        </script>

        





      
    
    



    
    </div>
</div>


<script>
    function updatePrice(value) {
      document.getElementById("maxPrice").textContent = "$" + value;
    }
</script>

{% endblock %}

arla/core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}
    Welcome to
{% endblock %}

{% block content %}
<h1 class="text-3xl font-bold">Welcome to Arla Racing Exhaust Indonesia</h1>
<p class="mb-12 text-lg">We are a leading manufacturer of exhaust systems for motorcycles.</p>
<div class="mt-6 px-6 pt-3 pb-12 bg-gray-100 rounded-xl">
    <h2 class="mb-3 text-2xl text-center">Newest Items</h2>
    <div class="grid sm:grid-cols-3 gap-3 ">
        {% for product in items %}
            <div>
                <a href="{% url 'item:detail' product.id %}">
                    <div>
                        <img src="{{ product.image.url }}" alt="{{ product.name }}" class="rounded-t-xl">
                    </div>
                    <div  class="bg-white sm:p-6 p-2 rounded-b-xl shadow-md">
                        <h3 class="sm:text-2xl text-md">{{ product.name }}</h3>
                        <p class="sm:text-md text-sm text-gray-500">Price: ${{ product.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>

<div class="mt-6 px-6 pt-3 pb-12 bg-gray-100 rounded-xl">
    <h2 class="mb-3 text-2xl text-center">Categories</h2>
    <div class="grid sm:grid-cols-3 gap-3 ">
        {% for category in categories %}
            <div>
                <a href="{% url 'category:category' category.name %}">
                    <div  class="bg-white sm:p-6 p-2 rounded-xl shadow-md">
                        <h3 class="sm:text-2xl text-md">{{ category.name }}</h3>
                        <p class="sm:text-md text-sm text-gray-500">{{ category.items.count }} items</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

arla/core/templates/core/login.html
{% extends "core/base.html" %}

{% block title %}Sign Up to {% endblock %}

{% block content %}
  <div class="sm:w-1/2 w-full my-6 p-6 mx-auto rounded-xl border border-black shadow-[5px_5px_0px_0px_rgba(0,0,0)]">

        <h1 class="mb-6 text-3xl">Log In</h1>
        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
            <label for="username" class="inline-block mb-2">Username</label><br>
            {{ form.username}} <br>

            <label for="password1" class="inline-block mb-2">Password</label><br>
            {{ form.password }} <br>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-2 bg-red-100 p-6 rounded-xl" role="alert">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
            
                
            {{ form.non_field_errors }}
                </div>
            {% endif %}
            </div>

            <button type="submit" class="mt-1 py-4 px-8 text-lg rounded-xl border border-black text-black shadow-[5px_5px_0px_0px_rgba(0,0,0)] hover:bg-blue-700 hover:text-white hover:shadow-[5px_5px_0px_0px_rgba(0,0,0)]">Log In</button>

            <p class="mt-6 ml-2 text-xs">Don't have an account? <a href="{% url 'core:signup' %}" class="text-blue-500 hover:text-blue-700">Sign Up</a></p>
            <p class="mt-2 ml-2 text-xs">Forgot your password? <a href="#" class="text-blue-500 hover:text-blue-700">Reset Password</a></p>
        </form>
        
  </div>
{% endblock %}

arla/core/templates/core/password.html
{% extends 'core/base.html' %}
{% block content %}
<div class="sm:w-1/2 w-full my-6 p-6 mx-auto rounded-xl border border-black shadow-[5px_5px_0px_0px_rgba(0,0,0)]">
        <h1 class="mb-6 text-3xl">Update Password</h1>
        <form method="POST" action="{% url 'core:password' %}">
            {% csrf_token %}
            <label for="password1" class="inline-block mb-2">New Password</label><br>
            {{ password_form.new_password1 }} <br>
            <label for="password2" class="inline-block mb-2">Repeat Password</label><br>
            {{ password_form.new_password2 }} <br>
<!-- 
            {% if password_form.errors or password_form.non_field_errors %} 
                <div class="mb-3 bg-red-100 p-6 rounded-xl" role="alert">

                {% for field in password_form %}
                    {{field.errors}}
                {% endfor %}
                
            {{ password_form.non_field_errors }}
                </div>
            {% endif %} -->

            <button type="submit" class="mt-1 py-2 px-5 text-sm bg-white rounded-xl border border-black text-black shadow-[2px_2px_0px_0px_rgba(0,0,0)] hover:bg-blue-700 hover:text-white hover:shadow-[2px_2px_0px_0px_rgba(0,0,0)]">Update Password</button>
        </form>
</div>

{% endblock %}

arla/core/templates/core/settings.html
{% extends 'core/base.html' %}
{% block content %}
<div class="sm:w-1/2 w-full my-6 p-6 mx-auto rounded-xl border border-blue-700 shadow-[5px_5px_0px_0px_rgba(29,78,216)]">

    <h1 class="mb-4 mt-2 text-3xl">Hi, {{user.username}}</h1>
    <form method="POST" action="{% url 'core:settings' %}">
    {% csrf_token %}
    {{ profile_form.as_p }}
    <button type="submit" class="mt-6 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Update Profile</button>
    <button type="button" class="mt-6 bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded"><a href="{% url 'core:password' %}">Change Password</a></button>
    </form>
</div>

{% endblock %}